hurst1 = 0.7 #1
hurst2 = 0.75#2
hurst3 = 0.8 #3
n_classes = 3 #three hurst value, 3 classes
fbm_method = "daviesharte"


#variables used by training, hyper parameters that can be turned for cross_validation
n_channels = 1 
gup_consumption = 0.3
learning_rate = 0.0001
keep_prob = 0.5
batch_size = 100       # Batch size
checkpoint_name ="checkpoints-cnn/brownian.ckpt"
#between 400 to 1000 epochs, accuracy only goes up for 4%, 600 is enough
epochs = 1000
#128/256/512 are tried, the higher, the better
seq_len = 256
#it decides how many brownian motions series are generated by each hurst value at training stage
count = 10000

#variables used by util
length = 2 #fbm related length / t = scale
plot = True


