hurst1 = 0.7 #1
hurst2 = 0.75#2
hurst3 = 0.8 #3
n_classes = 3
mfbm_method = "riemannliouville"


#variables used by training, hyper parameters that can be turned for cross_validation
n_channels = 1 
gup_consumption = 0.3
learning_rate = 0.0001
keep_prob = 0.5
batch_size = 200       # Batch size
checkpoint_name ="checkpoints-cnn/solution2/3digits/brownian.ckpt"
epochs = 400
#128/256/512 are tried, the higher, the better
seq_len = 256
#it decides how many brownian motions series are generated by each hurst value at training stage
count = 1000

#variables used by util
length = 1 #fbm related length / t = scale
plot = True


def h1(t):
    if t <= 0.5:
        return 0.2
    if 0.5 < t <= 0.7:
        return 0.2 + (t - 0.5)
    return 0.4

def h2(t):
    if t <= 0.5:
        return 0.4
    if 0.5 < t <= 0.7:
        return 0.4 - (t - 0.5)
    return 0.25



def h3(t):
    return 0.57