hurst1 = 0.7 #1
hurst2 = 0.75#2
hurst3 = 0.8 #3
n_classes = 3
fbm_method = "daviesharte"


#variables used by training, hyper parameters that can be turned for cross_validation
n_channels = 1 
gup_consumption = 0.3
learning_rate = 0.0001
keep_prob = 0.5
batch_size = 200       # Batch size
checkpoint_name ="checkpoints-cnn/solution2/3digits/brownian.ckpt"
epochs = 400
#128/256/512 are tried, the higher, the better
seq_len = 600
#it decides how many brownian motions series are generated by each hurst value at training stage
count = 2000

#variables used by util
length = 1 #fbm related length / t = scale
plot = True
